"""new fields in user model

Revision ID: 32871fb1698b
Revises: 4585def7e53a
Create Date: 2019-12-16 23:28:16.388996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32871fb1698b'
down_revision = '4585def7e53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
